fernetKey: aERBZE5MN3E0TjRjU2xzQWxCdTNIUks0WGFTZThoWXc=
webserverSecretKey: aERBZE5MN3E0TjRjU2xzQWxCdTNIUks0WGFTZThoWXc=

dags:
  gitSync:
    enabled: true
    repo: https://github.com/VipulShinkar/Airflow_Spark_Hudi.git
    branch: dev
    rev: HEAD
    depth: 1
    maxFailures: 0
    subPath: "dags"